In [1]:
from dsc2024 import datasets
from dsc2024 import handling

In [2]:
df_base = datasets.get_public_dataset(expand_metar_and_metaf=False)

In [3]:
df_base.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 302399 entries, 0 to 302398
Data columns (total 10 columns):
 #   Column                         Non-Null Count   Dtype
---  ------                         --------------   -----
 0   flightid                       302399 non-null  object
 1   hora_ref                       302399 non-null  datetime64[ns]
 2   origem                         302399 non-null  object
 3   destino                        302399 non-null  object
 4   url_img_satelite               298666 non-null  object
 5   metaf                          155737 non-null  object
 6   metar                          300770 non-null  object
 7   prev_troca_cabeceira           302399 non-null  int64
 8   troca_cabeceira_hora_anterior  302399 non-null  int64
 9   espera                         211679 non-null  float64
dtypes: datetime64[ns](1), float64(1), int64(2), object(6)
memory usage: 23.1+ MB

In [4]:
df_base.head()

,flightid,hora_ref,origem,destino,url_img_satelite,metaf,metar,prev_troca_cabeceira,troca_cabeceira_hora_anterior,espera
0,504a62621cd231d6ab67e674ce538cd3,2022-06-01 01:00:00,SBCF,SBFL,http://satelite.cptec.inpe.br/repositoriogoes/...,NaN,METAR SBFL 010000Z 17009KT 140V200 9999 BKN030...,0,1,0.0
1,b0fd0f83644625ecc21f5261e8e5e347,2022-06-01 01:00:00,SBPA,SBFL,http://satelite.cptec.inpe.br/repositoriogoes/...,NaN,METAR SBFL 010000Z 17009KT 140V200 9999 BKN030...,0,1,0.0
2,1210f0ca07ddca00d09a3e02d3b100d8,2022-06-01 01:00:00,SBSP,SBCF,http://satelite.cptec.inpe.br/repositoriogoes/...,NaN,METAR SBCF 010000Z 12006KT CAVOK 21/14 Q1018=,0,0,0.0
3,b25032f34507cce285ee779446496568,2022-06-01 01:00:00,SBGR,SBCT,http://satelite.cptec.inpe.br/repositoriogoes/...,NaN,METAR SBCT 010000Z 10006KT 7000 -RA BKN004 OVC...,0,0,0.0
4,00762a9892ecba7c66d1d87800d38cac,2022-06-01 01:00:00,SBSP,SBSV,http://satelite.cptec.inpe.br/repositoriogoes/...,NaN,METAR SBSV 010000Z 11008KT 9999 FEW023 27/21 Q...,0,1,0.0

In [22]:
df_train = datasets.get_train_dataset()

In [13]:
df_train.info()

<class 'pandas.core.frame.DataFrame'>
Index: 6991 entries, 54455 to 40144
Data columns (total 64 columns):
 #   Column                         Non-Null Count  Dtype
---  ------                         --------------  -----
 0   flightid                       6991 non-null   object
 1   hora_ref                       6991 non-null   datetime64[ns]
 2   origem                         6991 non-null   object
 3   destino                        6991 non-null   object
 4   url_img_satelite               6899 non-null   object
 5   prev_troca_cabeceira           6991 non-null   int64
 6   troca_cabeceira_hora_anterior  6991 non-null   int64
 7   espera                         6991 non-null   float64
 8   metar_station_id               6942 non-null   object
 9   metar_latitude                 6942 non-null   float64
 10  metar_longitude                6942 non-null   float64
 11  metar_elevation                6942 non-null   float64
 12  metar_date_time                6934 non-null   datetime64[ns]
 13  metar_wind_direction           6576 non-null   float64
 14  metar_wind_speed               6942 non-null   float64
 15  metar_wind_gust                70 non-null     float64
 16  metar_visibility               6942 non-null   float64
 17  metar_current_wx1              927 non-null    object
 18  metar_current_wx2              205 non-null    object
 19  metar_current_wx3              0 non-null      float64
 20  metar_skyc1                    4973 non-null   object
 21  metar_skylev1                  4826 non-null   float64
 22  metar_skyc2                    2835 non-null   object
 23  metar_skylev2                  2835 non-null   float64
 24  metar_skyc3                    902 non-null    object
 25  metar_skylev3                  902 non-null    float64
 26  metar_skyc4                    65 non-null     object
 27  metar_skylev4                  65 non-null     float64
 28  metar_cloudcover               6942 non-null   float64
 29  metar_temperature              6932 non-null   float64
 30  metar_dewpoint                 6926 non-null   float64
 31  metar_altimeter                6933 non-null   float64
 32  metar_current_wx1_symbol       6942 non-null   float64
 33  metar_current_wx2_symbol       6942 non-null   float64
 34  metar_current_wx3_symbol       6942 non-null   float64
 35  metar_remarks                  6942 non-null   object
 36  metaf_station_id               2923 non-null   object
 37  metaf_latitude                 2923 non-null   float64
 38  metaf_longitude                2923 non-null   float64
 39  metaf_elevation                2923 non-null   float64
 40  metaf_date_time                2923 non-null   datetime64[ns]
 41  metaf_wind_direction           2923 non-null   float64
 42  metaf_wind_speed               2923 non-null   float64
 43  metaf_wind_gust                0 non-null      float64
 44  metaf_visibility               2923 non-null   float64
 45  metaf_current_wx1              788 non-null    object
 46  metaf_current_wx2              0 non-null      object
 47  metaf_current_wx3              0 non-null      float64
 48  metaf_skyc1                    1668 non-null   object
 49  metaf_skylev1                  1668 non-null   float64
 50  metaf_skyc2                    59 non-null     object
 51  metaf_skylev2                  59 non-null     float64
 52  metaf_skyc3                    0 non-null      float64
 53  metaf_skylev3                  0 non-null      float64
 54  metaf_skyc4                    0 non-null      float64
 55  metaf_skylev4                  0 non-null      float64
 56  metaf_cloudcover               2923 non-null   float64
 57  metaf_temperature              2895 non-null   float64
 58  metaf_dewpoint                 2895 non-null   float64
 59  metaf_altimeter                2895 non-null   float64
 60  metaf_current_wx1_symbol       2923 non-null   float64
 61  metaf_current_wx2_symbol       2923 non-null   float64
 62  metaf_current_wx3_symbol       2923 non-null   float64
 63  metaf_remarks                  2923 non-null   object
dtypes: datetime64[ns](3), float64(41), int64(2), object(18)
memory usage: 3.5+ MB

In [14]:
df_train.head()

,flightid,hora_ref,origem,destino,url_img_satelite,prev_troca_cabeceira,troca_cabeceira_hora_anterior,espera,metar_station_id,metar_latitude,...,metaf_skyc4,metaf_skylev4,metaf_cloudcover,metaf_temperature,metaf_dewpoint,metaf_altimeter,metaf_current_wx1_symbol,metaf_current_wx2_symbol,metaf_current_wx3_symbol,metaf_remarks
54455,5fa9a19e5f54651b2efa9228f0b90f70,2022-08-09 15:00:00,SBSP,SBCT,http://satelite.cptec.inpe.br/repositoriogoes/...,0,1,0.0,SBCT,-25.52,...,NaN,NaN,8.0,13.0,13.0,30.002463,61.0,0.0,0.0,
105182,ce6b915353862b0045c102fb6678f589,2022-10-13 10:00:00,SBGL,SBGR,http://satelite.cptec.inpe.br/repositoriogoes/...,0,0,0.0,SBGR,-23.42,...,NaN,NaN,0.0,21.0,13.0,30.031993,0.0,0.0,0.0,
131129,1a363ebe75c29360effcbc626a17cb39,2022-11-13 19:00:00,SBRJ,SBGR,http://satelite.cptec.inpe.br/repositoriogoes/...,1,0,0.0,SBGR,-23.42,...,NaN,NaN,0.0,30.0,11.0,29.766223,0.0,0.0,0.0,
82569,d5b1d305160389ea8331225e8fc2531c,2022-09-14 15:00:00,SBPA,SBKP,http://satelite.cptec.inpe.br/repositoriogoes/...,1,0,0.0,SBKP,-23.00,...,NaN,NaN,8.0,24.0,17.0,30.120583,63.0,0.0,0.0,
199409,5b24ab7100c89990b180c6b7fc5def4b,2023-02-02 11:00:00,SBSP,SBFL,http://satelite.cptec.inpe.br/repositoriogoes/...,1,0,0.0,SBFL,-27.67,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,None

In [15]:
df_train

,flightid,hora_ref,origem,destino,url_img_satelite,prev_troca_cabeceira,troca_cabeceira_hora_anterior,espera,metar_station_id,metar_latitude,...,metaf_skyc4,metaf_skylev4,metaf_cloudcover,metaf_temperature,metaf_dewpoint,metaf_altimeter,metaf_current_wx1_symbol,metaf_current_wx2_symbol,metaf_current_wx3_symbol,metaf_remarks
54455,5fa9a19e5f54651b2efa9228f0b90f70,2022-08-09 15:00:00,SBSP,SBCT,http://satelite.cptec.inpe.br/repositoriogoes/...,0,1,0.0,SBCT,-25.52,...,NaN,NaN,8.0,13.0,13.0,30.002463,61.0,0.0,0.0,
105182,ce6b915353862b0045c102fb6678f589,2022-10-13 10:00:00,SBGL,SBGR,http://satelite.cptec.inpe.br/repositoriogoes/...,0,0,0.0,SBGR,-23.42,...,NaN,NaN,0.0,21.0,13.0,30.031993,0.0,0.0,0.0,
131129,1a363ebe75c29360effcbc626a17cb39,2022-11-13 19:00:00,SBRJ,SBGR,http://satelite.cptec.inpe.br/repositoriogoes/...,1,0,0.0,SBGR,-23.42,...,NaN,NaN,0.0,30.0,11.0,29.766223,0.0,0.0,0.0,
82569,d5b1d305160389ea8331225e8fc2531c,2022-09-14 15:00:00,SBPA,SBKP,http://satelite.cptec.inpe.br/repositoriogoes/...,1,0,0.0,SBKP,-23.00,...,NaN,NaN,8.0,24.0,17.0,30.120583,63.0,0.0,0.0,
199409,5b24ab7100c89990b180c6b7fc5def4b,2023-02-02 11:00:00,SBSP,SBFL,http://satelite.cptec.inpe.br/repositoriogoes/...,1,0,0.0,SBFL,-27.67,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,None
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5071,ba3c7bb64f527960c0ea720a64629075,2022-06-07 20:00:00,SBSV,SBBR,http://satelite.cptec.inpe.br/repositoriogoes/...,1,1,0.0,SBBR,-15.87,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,None
79648,c3f7a2d473b6d5fc5917efe8188db6a8,2022-09-10 22:00:00,SBRJ,SBSP,http://satelite.cptec.inpe.br/repositoriogoes/...,0,1,0.0,SBSP,-23.62,...,NaN,NaN,8.0,16.0,15.0,29.943403,10.0,0.0,0.0,
31123,c237471ecb0bf18cf7ff3cd3a041b29a,2022-07-11 20:00:00,SBRJ,SBCT,http://satelite.cptec.inpe.br/repositoriogoes/...,1,1,0.0,SBCT,-25.52,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,None
175081,dda3f2efc48caa12b12bd35ceac0438b,2023-01-04 18:00:00,SBSP,SBRJ,http://satelite.cptec.inpe.br/repositoriogoes/...,0,0,0.0,SBRJ,-22.88,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,None
40144,1d3d7c1b320be2723cadf0582c143710,2022-07-22 18:00:00,SBSP,SBRJ,http://satelite.cptec.inpe.br/repositoriogoes/...,0,1,0.0,SBRJ,-22.88,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,None

In [16]:
df_train.origem.value_counts()

origem
SBSP    1199
SBRJ     966
SBGR     878
SBBR     643
SBCF     622
SBKP     554
SBPA     497
SBCT     422
SBRF     387
SBSV     384
SBFL     293
SBGL     146
Name: count, dtype: int64

In [17]:
df_train.destino.value_counts()

destino
SBSP    1158
SBRJ    1019
SBGR     806
SBBR     701
SBCF     628
SBPA     545
SBKP     466
SBCT     459
SBSV     416
SBRF     365
SBFL     285
SBGL     143
Name: count, dtype: int64

In [19]:
df_train.metaf_date_time

54455    2022-08-09 15:00:00
105182   2022-10-13 10:00:00
131129   2022-11-13 19:00:00
82569    2022-09-14 15:00:00
199409                   NaT
                 ...
5071                     NaT
79648    2022-09-10 22:00:00
31123                    NaT
175081                   NaT
40144                    NaT
Name: metaf_date_time, Length: 6991, dtype: datetime64[ns]

In [21]:
df_train.metar_date_time

54455    2022-08-09 14:00:00
105182   2022-10-13 09:00:00
131129   2022-11-13 18:00:00
82569    2022-09-14 14:00:00
199409   2023-02-02 10:00:00
                 ...
5071     2022-06-07 19:00:00
79648    2022-09-10 21:00:00
31123    2022-07-11 19:00:00
175081   2023-01-04 17:00:00
40144    2022-07-22 17:00:00
Name: metar_date_time, Length: 6991, dtype: datetime64[ns]

In [20]:
df_train.hora_ref

54455    2022-08-09 15:00:00
105182   2022-10-13 10:00:00
131129   2022-11-13 19:00:00
82569    2022-09-14 15:00:00
199409   2023-02-02 11:00:00
                 ...
5071     2022-06-07 20:00:00
79648    2022-09-10 22:00:00
31123    2022-07-11 20:00:00
175081   2023-01-04 18:00:00
40144    2022-07-22 18:00:00
Name: hora_ref, Length: 6991, dtype: datetime64[ns]

In [ ]:
# hora_ref, date_time and date_time_metaf are the same